### ISSUE TITLE
Unable to merge dex

### ISSUE THREAD

**Issue by younas-bangash** [CreativeSDK/android-getting-started-samples#53]
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.2"
    defaultConfig {
        applicationId "com.abc.appid"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        manifestPlaceholders = [appPackageName: "${applicationId}"]
        multiDexEnabled true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    packagingOptions {
        exclude 'META-INF/DEPENDENCIES.txt'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/notice.txt'
        exclude 'META-INF/license.txt'
        exclude 'META-INF/dependencies.txt'
    }

    dataBinding {
        enabled = true
    }

    dexOptions {
        jumboMode true
    }
}

dependencies {
//    implementation 'com.google.firebase:firebase-messaging:11.4.2'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })

    compile group: 'com.squareup.retrofit2', name: 'adapter-rxjava', version: '2.2.0'
    compile group: 'com.squareup.retrofit2', name: 'converter-gson', version: '2.2.0'
    compile group: 'com.squareup.okhttp3', name: 'logging-interceptor', version: '3.7.0'
    compile 'io.reactivex:rxandroid:1.2.1'

    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:design:26.1.0'
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.airbnb.android:lottie:2.2.5'

    /* Firebase Libraries */
    compile 'com.google.firebase:firebase-auth:11.4.2'
    compile 'com.google.firebase:firebase-core:11.4.2'
    compile 'com.google.firebase:firebase-crash:11.4.2'
    compile 'com.google.firebase:firebase-config:11.4.2'

    /* Add the CSDK framework*/
    compile 'com.adobe.creativesdk.foundation:auth:0.9.1251'
    compile 'com.adobe.creativesdk:image:4.8.4'
    compile 'com.localytics.android:library:3.8.0'

    compile 'com.orhanobut:hawk:2.0.1'
    compile('com.sangcomz:FishBun:0.7.7@aar') {
        transitive = true
    }
    testCompile 'junit:junit:4.12'
}
apply plugin: 'com.google.gms.google-services'
```

When I try to run or build the code it gives me error
```

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
```

**Comment by abeemukthees** [comment]
I'm also facing the same issue. Any fix?

**Comment by royorange** [comment]
Facing the same issue after upgrade AS to 3.0. And seems that the sdk used the 'AsyncTaskCompat' which is deprecated.It will cause the app crash.

 java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/os/AsyncTaskCompat;
             at com.adobe.creativesdk.aviary.AdobeImageEditorActivityAbstract.loadTools(AdobeImageEditorActivityAbstract.java:760)
             at com.adobe.creativesdk.aviary.AdobeImageEditorActivityAbstract.onPostCreate(AdobeImageEditorActivityAbstract.java:579)
             at android.app.Instrumentation.callActivityOnPostCreate(Instrumentation.java:1207)

**Comment by sagartrehan** [comment]
This repo seems to be no longer active. We are facing random crashes in application after integrating this in latest Android OS.

**Comment by pawandeepka** [comment]
The same issue does not have any solution. :(

**Comment by ErinFinnegan** [comment]
Hi there! 

This repo is no longer active. We've been doing some messaging about EOL of the Creative SDK. Here is the most recent email:

> We’re reaching out with an important update about the Creative SDK. Adobe is ending support for the Creative SDK Content Management, Workflow, and Authentication components for iOS, Android, and Web.
> 
> Existing integrations of the Creative SDK should continue to work, as we’re not shutting down core services behind the Creative SDK at this time. However, the underlying platform and APIs will be evolving over the next 12-24 months, so we are no longer building the Creative SDK. Therefore, in the best interest of our developer community, we're no longer supporting new integrations of it.
> 
> Here are more details on the end of support to help you plan:

> - Adobe is ending support for the Creative SDK Content Management, Workflow, and Authentication components for iOS, Android, and Web. The specific Creative SDK features within these components include the Asset Browser UI, CC Files API, CC Libraries API, Lighroom Photos API, Typekit (Fonts) UI, PSD file type read/write, AI file type write, Send to Desktop, and Authentication.
> - Existing integrations of the Creative SDK Content Management, Workflow, and Authentication components should continue to work, as we're not deprecating core services behind the Creativew SDK.
> - Over the next few months, Adobe will remove the Creative SDK overview pages, documentation, and GitHub repos.
> - At this point, Adobe is no longer providing developer support for partners working on Creative SDK integrations. Over the next few months, Adobe will remove the Creative SDK Support Center.
> - Adobe is no longer reviewing Creative SDK Production Mode ID requests submitted through the Adobe I/O Console.
> - For partners using the Typekit UI, we recommend that you migrate to the [Adobe Fonts platform](https://www.adobe.io/apis/creativecloud/adobe-fonts.html) as soon as possible.
> - [Authentication workflows](https://www.adobe.io/authentication.html) will continue to be available and Creative SDK scopes will continue to be supported.
> 
> 
> The existing services behind the Creative SDK will continue to function. For most of the Creative SDK features, we do not offer an alternative today. We plan on introducing new APIs that will serve as an alternative for many Creative SDK-powered features in the future.
